---
- hosts: all
  become: yes
  tasks:
    - name: install apache2
      apt: name=apache2 update_cache=yes state=latest
    - name: install apache2
      apt: name=apache2 update_cache=yes state=latest
    - name: enabled mod_rewrite
      apache2_module: name=rewrite state=present
      notify:
        - restart apache2
  handlers:
    - name: restart apache2
      service: name=apache2 state=restarted
    - name: install apache2
      apt: name=apache2 state=latest
    - name: enabled mod_rewrite
      apache2_module: name=rewrite state=present
    - name: apache2_8081
      lineinfile: dest=/etc/apache2/ports.conf regexp="^Listen 80" line="Listen 8081"
        state=present
      notify:
        - restart apache2
    - name: apache2_8081
      lineinfile: dest=/etc/apache2/sites-available/000-default.conf
        regexp="^<VirtualHost \*:80>" line="<VirtualHost *:8081>" state=present
      notify:
        - restart apache2
     
